version: "3.8"

networks:
  klura_network_test:
    driver: bridge

services:
  redis:
    image: "redis:6.0"
    container_name: klura_redis_test
    expose:
      - "6379"
    networks:
      - klura_network_test

  postgres:
    image: "postgres:13.1"
    container_name: klura_postgres_test
    expose:
      - "5432"
    restart: on-failure
    volumes:
      - ../data/test/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - klura_network_test

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: klura_backend:test
    container_name: klura_backend_test
    command: yarn run run-jest
    expose:
      - "4000"
    depends_on:
      - redis
      - postgres
    volumes:
      - ..:/usr/app/backend
    environment:
      NETWORK: Klura
      SERVER: Test
      NODE_ENV: development
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    networks:
      - klura_network_test
