version: "3.8"

networks:
  klura_network:
    driver: bridge

services:
  redis:
    image: "redis:6.0"
    container_name: klura_redis
    expose:
      - "6379"
    restart: unless-stopped
    networks:
      - klura_network

  postgres:
    image: "postgres:13.1"
    container_name: klura_postgres
    expose:
      - "5432"
    restart: unless-stopped
    volumes:
      - ../data/prod/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - klura_network

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: klura_backend:prod
    container_name: klura_backend
    command: yarn start
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    environment:
      NETWORK: Klura
      SERVER: Production
      NODE_ENV: production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    networks:
      - klura_network
